# Project specific auto-labeler

area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
area/github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
