# Area (project specific)
- name: "area/github"
  color: "#fbca04"
  description: "Affecting the .github folder, so CI/CD and such"
- name: "area/docs"
  color: "#70C4BE"
  description: "Affecting the documentation of the project"

# Status
- name: "status/done"
  color: "#0E8A16"
  description: "The new feature or request has been implemented"
- name: "status/hold"
  color: "#56be82"
  description: "This has been put on hold"
- name: "status/blocked"
  color: "#ffadad"
  description: "Blocked by external factors or dependencies"
- name: "status/needs-review"
  color: "#fbca04"
  description: "Needs code or design review"
- name: "status/invalid"
  color: "#e4e669"
  description: "This doesn't seem right"
- name: "status/waiting-for-author"
  color: "#B0D66E"
  description: "Waiting for a reply from the author to further investigate"
- name: "status/wont-do"
  color: "#ffffff"
  description: "This will not be worked on"

# Kind
- name: "kind/enhancement"
  color: "#a2eeef"
  description: "New feature or request"
- name: "kind/bug"
  color: "#d73a4a"
  description: "Something isn't working"
- name: "kind/duplicate"
  color: "#cfd3d7"
  description: "This issue or pull request already exists"
- name: "kind/question"
  color: "#d876e3"
  description: "Further information is requested"
- name: "kind/spam"
  color: "#a8031d"
  description: "This issue/PR is spam"
- name: "kind/sticky"
  color: "#456105"
  description: "This is a sticky issue, so that people are more aware of it"
- name: "kind/typo"
  color: "#AA703C"
  description: "A typo has been found"
- name: "kind/refactor"
  color: "#8e44ad"
  description: "Internal improvement without functional change"
- name: "kind/deprecation"
  color: "#ff9f43"
  description: "Feature or API is being deprecated"

# Priority
- name: "priority/critical"
  color: "#cba6f7"
  description: "This has a critical priority"
- name: "priority/important"
  color: "#f38ba8"
  description: "This has an important priority"
- name: "priority/low"
  color: "#a6e3a1"
  description: "This has a low priority"
- name: "priority/medium"
  color: "#fab387"
  description: "This has a medium priority"

# Sizes
- name: "size/XXL"
  color: "#E50009"
- name: "size/XL"
  color: "#C32607"
- name: "size/L"
  color: "#A14C05"
- name: "size/M"
  color: "#7F7203"
- name: "size/S"
  color: "#5D9801"
- name: "size/XS"
  color: "#3CBF00"

# Other
- name: "ai-slop"
  color: "#9ea4f3"
  description: "AI slop is worse than non-fancy code"
- name: "good-first-issue"
  color: "#7057ff"
  description: "Good for newcomers"
- name: "help-wanted"
  color: "#008672"
  description: "Extra attention is needed"
- name: "skill-issue"
  color: "#1f60f3"
  description: "Why read when you can ask"
